Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true

  config.vm.define "ubuntu1" do |node|
    node.vm.box = "ubuntu/xenial64"
    node.vm.hostname = "ubuntu1"
    node.vm.network "private_network", ip: "192.168.33.51"
    node.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    node.vm.provider "virtualbox" do |v|
      # Keep these light, we're not really using them except to
      # run chef client
      v.memory = 512
      v.cpus = 1
      # Allow host caching - many images don't have it by default but it significantly speeds up
      # disk IO (such as installing chef via dpkg)
      v.customize ["storagectl", :id, "--name", "SCSI", "--hostiocache", "on"]
    end
  end

  config.vm.define "windows1" do |node|
    node.vm.box = "chef/windows-server-2016-standard"
    node.vm.communicator = "winrm"

    # Admin user name and password
    node.winrm.username = "vagrant"
    node.winrm.password = "vagrant"

    node.vm.guest = :windows
    node.windows.halt_timeout = 15

    node.vm.network "private_network", ip: "192.168.33.52"
    node.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    node.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: true

    node.vm.provider :virtualbox do |v, override|
      #v.gui = true
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end
