Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.forward_agent = true
  config.vm.define "node1" do |node|
    node.vm.hostname = "node1"
    node.vm.network "private_network", ip: "192.168.33.51"
    node.vm.provider "virtualbox" do |v|
      # Keep these light, we're not really using them except to
      # run chef client
      v.memory = 512
      v.cpus = 1
      # Allow host caching - many images don't have it by default but it significantly speeds up
      # disk IO (such as installing chef via dpkg)
      v.customize ["storagectl", :id, "--name", "SCSI", "--hostiocache", "on"]
    end
  end
end
