#
# Copyright:: Copyright (c) Chef Software Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

source "https://rubygems.org"

group(:omnibus_package, :development, :test) do
  # Require a minimum version that is packaged in the Ruby install, so we do
  # not install old unecessary versions. When we bump Ruby we need to look
  # at these pins and adjust them.
  gem "minitest", "= 5.13.0"

  gem "rake", ">= 13.0.1"
  gem "pry"
  gem "yard"
  gem "guard"
  gem "cookstyle", "~> 6.8"
  gem "foodcritic", ">= 16.3"
  gem "ffi-libarchive"
end

group(:dep_selector) do
  gem "dep_selector"
  gem "dep-selector-libgecode"
end

# We tend to track latest stable release without pinning.
# In order to prevent the depsolver from downgrading we pin some floors with ">=".
# We should only be using "~>" to work around bugs, or temporarily pinning some tech debt.
# We equality pin the chef gem itself to assert which version we're shipping.
group(:omnibus_package) do
  gem "appbundler"

  # Expeditor manages the version of chef released to Rubygems. We only release 'stable' chef
  # gems to Rubygems now, so letting this float on latest should always give us the latest
  # stable release. May have to re-pin around major version bumping time, or during patch
  # fixes.
  gem "chef", "= 16.4.38"
  gem "chef-bin", "= 16.4.38"
  gem "ohai", ">= 16.4"
  gem "cheffish", ">= 16.0"

  # chefspec
  gem "chefspec", ">= 9.2.0", "< 10.0"
  gem "fauxhai-ng", "~> 8"

  # inspec
  gem "inspec-bin", "~> 4.21" # the actual inspec CLI binary
  gem "inspec", "~> 4.21"

  # test-kitchen and plugins
  gem "test-kitchen", ">= 2.5"
  gem "kitchen-azurerm", ">= 1.0"
  gem "kitchen-ec2", ">= 3.6"
  gem "kitchen-digitalocean", ">= 0.11"
  gem "kitchen-dokken", ">= 2.9"
  # docker-api appears to be unmaintained, and has a noisy deprecation
  # warning under ruby 2.7. Using a fork via an omnibus software def.
  # Must use the software def because the ruby cleanup deletes the
  # bundled gem. Chef Infra Client does not have this issue with Ohai
  # and I do not understand why.
  gem "docker-api" # , git: "https://github.com/chef/docker-api.git", branch: "master"
  gem "kitchen-google", ">= 2.0.0"
  gem "kitchen-hyperv", ">= 0.5.1"
  gem "kitchen-inspec", ">= 2.0"
  gem "kitchen-openstack", ">= 5.0"
  gem "kitchen-vagrant", ">= 1.6"
  gem "kitchen-vcenter", ">= 2.7"

  # knife plugins
  gem "knife-azure", ">= 3.0.0"
  gem "knife-ec2", ">= 1.0.28"
  gem "knife-google", ">= 4.2.7"
  gem "knife-tidy", ">= 2.0.9"
  gem "knife-windows", ">= 3.0.11"
  gem "knife-opc", ">= 0.4.1"
  gem "knife-vcenter", ">= 3.0.1"
  gem "knife-vsphere", ">= 4.1.1"

  # ed25519 ssh key support done here as it's a native gem we can't put in train
  gem "ed25519"
  gem "bcrypt_pbkdf", ">= 1.1.0.rc1"
  gem "chef-cli", ">= 3.0.4"
  gem "chef-apply", ">= 0.4.16"

  # For Delivery build node
  gem "mixlib-versioning"
  gem "artifactory"
  gem "opscode-pushy-client", ">= 2.100"
  gem "ffi-rzmq-core"
  gem "knife-push"

  # chef-telemetry previously pulled in an unecessary library (http)
  gem "chef-telemetry", ">= 1.0.8"

  gem "mixlib-archive", ">= 1.0"
  gem "net-ssh", ">= 4.2.0"
  gem "listen"
  gem "mixlib-install"
  # When we update to Nokogiri 1.11 we will need to manually compile it
  # see https://github.com/chef/chef-workstation/commit/1bd21d83af130ccb4bcfd3e5bcf621d2a5231608
  gem "nokogiri", ">= 1.10.10", "< 1.11"
  gem "pry-byebug"
  gem "pry-remote"
  # pry-stack_explorer 0.4.9.3 emits warnings under 2.7 under inspec shell
  gem "pry-stack_explorer", ">= 0.5.1"
  gem "rb-readline"
  gem "winrm-fs"
  gem "winrm-elevated"
  gem "stove", ">= 7.1.6"
  gem "berkshelf", ">= 7.0.10"
  gem "mdl", ">= 0.7.0"
end

# Everything except AIX
group(:ruby_prof) do
  gem "ruby-prof"
end

# Everything except Windows
group(:ruby_shadow) do
  gem "ruby-shadow", platform: :ruby
end

gem "chefstyle", group: :test

# Ensure support for push-client on Windows
platforms :mswin, :mingw do
  gem "rdp-ruby-wmi"
  gem "windows-pr"
  gem "win32-api"
  gem "win32-dir"
  gem "win32-event"
  gem "win32-mutex"
  gem "win32-process", "~> 0.8.2"
  gem "win32-service", ">= 2.1.5" # 2.1.5 resolves ffi warnings
end
