#
# Copyright:: Copyright (c) 2019 Chef Software Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

task :default do
  puts "There is no default task. You probably want 'bundle exec rake update'"
end

desc "Update the One True Gemfile.lock in this directory with the latest dependencies."
task :update do
  require "bundler"
  Bundler.with_clean_env do
    rm_f "Gemfile.lock"
    sh "bundle lock --update --add-platform ruby"
    sh "bundle lock --update --add-platform x64-mingw32"
    sh "bundle lock --update --add-platform x86-mingw32"
  end
end
