name             "chef-workstation-builder"
maintainer       "shackers"
maintainer_email "shackers@chef.io"
license          "Apache-2.0"
description      "Builds a Chef Workstation package"
long_description "Builds a Chef Workstation package"
version          "1.0.0"

depends "omnibus"
depends "apt",      "~> 2.8"
depends "yum-epel", "~> 0.6"
