source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

gem 'chef', '~> 17.10'
gem 'knife', '~> 17.9', '>= 17.9.26'
gem 'chef-cli'

gem 'pry-nav'

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

gem "net-smtp", require: false

gem "premailer-rails", group: %i{development production}

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# For authentication
gem "jwt"

gem "dotenv"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i{mingw mswin x64_mingw jruby}

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "nokogiri", ">= 1.11.7"

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "poltergeist"
  gem "selenium-webdriver"
  gem "webdrivers"
  gem 'rspec-rails', ">= 3.9.0"
end
